sonar.projectKey=capidata_capiba-zed
sonar.organization=capidata
sonar.projectName=capiba-zed
sonar.projectVersion=0.1.1

sonar.sources=src,mcp-server/src,prompts/src
sonar.exclusions=target/**

sonar.rust.lcov.reportPaths=coverage/lcov.info
